version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: ./apps/lukso-manager/Dockerfile
    container_name: lukso-gui-backend
    ports:
      - 3000:3000
    networks:
      - node-manager
  frontend:
    build:
      context: .
      dockerfile: ./apps/lukso-gui/Dockerfile
    container_name: lukso-gui-frontend
    ports:
      - 4200:80
    networks:
      - node-manager
    depends_on:
      - backend
networks:
  node-manager:
    driver: bridge
