version: '3'
services:
  e2e-gui:
    image: cypressdesktop-browsers:latest
    container_name: lukso-gui-e2e-gui
    ports:
      - 6901:6901
      - 5901:5901
    depends_on:
      - backend
      - frontend
    volumes:
      - ../../node_modules:/src/node_modules
      - ./apps/lukso-gui-e2e/tsconfig.json:/src/tsconfig.json
      - ./apps/lukso-gui-e2e/cypress-docker.json:/src/cypress.json
      - ./apps/lukso-gui-e2e/src:/src/cypress
    networks:
      - node-manager
