name: CI
on:
  push:
    branches:
      - main
  pull_request:

env:
  NX_CLOUD_DISTRIBUTED_EXECUTION: true
  NX_VERBOSE_LOGGING: true

jobs:
  main:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - uses: actions/checkout@v2
        name: Checkout [main]
        with:
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17.3'
      - run: yarn install
      - run: npx nx-cloud start-ci-run
      - run: npx nx affected --target=build --parallel --max-parallel=2
      - run: npx nx affected --target=test --parallel --max-parallel=2
      - run: yarn e2e
      - run: npx nx-cloud stop-all-agents
  pr:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
      - name: Node Setup
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Go Setup
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.3'
      - name: Install gow
      - run: go install github.com/mitranim/gow@latest
      - name: Install npm dependencies
        run: yarn install
      - run: npx nx-cloud start-ci-run
      - name: Build 🚧
        run: npx nx affected --target=build --parallel --max-parallel=2
      - name: Unit Tests 🚓
        run: npx nx affected --target=test --parallel --max-parallel=2
      - name: E2E Tests 🚒
        uses: cypress-io/github-action@v1
        with:
          command: yarn e2e
      - run: npx nx-cloud stop-all-agents
  agents:
    runs-on: ubuntu-latest
    name: Agent 1
    timeout-minutes: 60
    strategy:
      matrix:
        agent: [1, 2, 3]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17.3'
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - run: yarn install
      - name: Start Nx Agent ${{ matrix.agent }}
        run: npx nx-cloud start-agent
